type Env = 
    'DISCORD_TOKEN' |
    'DISCORD_GUILD_ID' |
    'DISCORD_BOT_APP_ID' |
    'TWITCH_USERNAME' |
    'TWITCH_OAUTH' |
    'TWITCH_CHANNEL' |
    'MYSQL_USERNAME' |
    'MYSQL_PASSWORD' |
    'MYSQL_DATABASE' |
    'MYSQL_HOST' |
    'APPLY_CHANNEL_ID' |
    'CLAN_APPLICATIONS_CATEGORY' |
    'STAFF_ROLE' |
    'OWNER_ROLE' |
    'APPLICANTS_CHANNEL_ID' |
    'APP_ROLE' |
    'CLAN_MEMBER_ROLE' |
    'STREAM_CHAT_CHANNEL' |
    'COMMUNITY_MEMBER_ROLE' |
    'GUILD_ID' |
    'TRIALISTS_CHANNEL_ID' |
    'NEW_MEMBERS_CHANNEL_ID' |
    'EXPEL_ASAP_CHANNEL_ID' |
    'MEMBERS_CATEGORY_ID' |
    'MEMES_CHANNEL_ID' |
    'RARE_DROPS_CHANNEL_ID' |
    'ACHIEVEMENTS_CHANNEL_ID' |
    'RANKUPS_CHANNEL_ID' |
    'CLAN_FRIEND_ROLE' |
    'ALLROUND_IRONMAN_CHANNEL_ID' |
    'ARCHIVE_CATEGORY' |
    'IconIDClanFriend' |
    'IconIDRecruit' |
    'IconIDCorporal' |
    'IconIDSergeant' |
    'IconIDLieutenant' |
    'IconIDCaptain' |
    'IconIDGeneral' |
    'IconIDOfficer' |
    'IconIDCommander' |
    'IconIDColonel' |
    'IconIDBrigadier' |
    'IconIDAdmiral' |
    'IconIDChampion' |
    'IconIDHero' |
    'IconIDLegend' |
    'IconIDMyth' |
    'IconIDSkiller' |
    'IconIDClogger' |
    'IconIDGrandmaster' |
    'IconRoleClanFriend' |
    'IconRoleRecruit' |
    'IconRoleCorporal' |
    'IconRoleSergeant' |
    'IconRoleLieutenant' |
    'IconRoleCaptain' |
    'IconRoleGeneral' |
    'IconRoleOfficer' |
    'IconRoleCommander' |
    'IconRoleColonel' |
    'IconRoleBrigadier' |
    'IconRoleAdmiral' |
    'IconRoleChampion' |
    'IconRoleHero' |
    'IconRoleLegend' |
    'IconRoleMyth' |
    'IconRoleSkiller' |
    'IconRoleClogger' |
    'IconRoleGrandmaster' |
    'YTDL_NO_UPDATE'